// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJ-7F9utFfXJmlK7bxPDVLDBzxUMedsuE',
    appId: '1:82637475051:android:be51de58ae7e44cddb42ae',
    messagingSenderId: '82637475051',
    projectId: 'eyo-time-management',
    storageBucket: 'eyo-time-management.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgBBr1PgkC-Xi_q5Q7XZZT3tS4UMokiRQ',
    appId: '1:82637475051:ios:2f0c42964c7bc4f2db42ae',
    messagingSenderId: '82637475051',
    projectId: 'eyo-time-management',
    storageBucket: 'eyo-time-management.firebasestorage.app',
    androidClientId: '82637475051-p04ikf7s6bnvcnmddnmfc2oq8n3lagvf.apps.googleusercontent.com',
    iosClientId: '82637475051-150ruq6rkap9c75cgh2e227k3a76l0g6.apps.googleusercontent.com',
    iosBundleId: 'com.eyogroup.timeManagement',
  );

}